
# compose for the frontend && backend application
services:
  frontend:
    image: frontend #note: THIS MUST BE CREATED BY THE FRONTEND FIRST
    command: npm start
    ports:
      - "3000:3000"
  backend:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"

    environment:
       FRONTEND.URL: frontend
       FRONTEND.PORT: 3000
       OUATH2.URL: mock-oauth2-server
       OUATH2.PORT: 8282

  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server:2.1.0
    ports:
      - "8282:8282"
    volumes:
      - ./src/main/resources/application.yaml:/app/application.yaml
    environment:
      LOG_LEVEL: "debug"
      SERVER_PORT: 8282 #todo configure global variable
