
# compose for the frontend && backend application, if you want complete independce from the frontend, you can comment out line 4 - 8
services:

  frontend:
    image: frontend #note: THIS MUST BE CREATED BY THE FRONTEND FIRST see the dockerfile https://github.com/Bad-chelor-ITPE3200/NAV-IT-SIF-bachelor-frontend/blob/main/Dockerfile
    command: npm start
    ports:
      - "3000:3000"
#    networks:
#      - oauth2server
    environment:
     REACT_APP_TOKEN_URL: http://localhost:8282/default/token #here you can change to whatever oauth2server you want to use
     REACT_APP_BASE_URL: http://localhost:8080
  backend:
    build:
      #Remember to create a jar, look at REAMDE
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"

    environment:
       FRONTEND.URL: localhost
       FRONTEND.PORT: 3000
       mock-oauth2-server.url: mock-oauth2-server #remember to change this one too, with the right port
       mock-oauth2-server.port: 8282
       db.url : localhost
       db.port : 8082
       db.files : "/vju/__files"
       #if you want  to change the entire service url, you can look at db.Service global variable
       #IMPORTANT::: CHANGE the file location for the wiremock server to /vju/__files from ., and back when you dont need it anymore

  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server:2.1.0
    ports:
      - "8282:8282"
    volumes:
      - ./src/main/resources/application.yaml:/app/application.yaml
#      to use the right ouath2server in the frontend:
#    networks:
#      oauth2server:
#        aliases:
#          - ouath2server
    environment:
      LOG_LEVEL: "debug"
      SERVER_PORT: 8282
