
# compose for the back end application
services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"
#    volumes: #this can be commended out when wiremock is not in use
#      - ./src/main/resources/__files:/resources/__files

  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server:2.1.0
    ports:
      - "8282:8282"
    volumes:
      - ./src/main/resources/application.yaml:/app/application.yaml
    environment:
      LOG_LEVEL: "debug"
      SERVER_PORT: 8282 #todo configure global variable
