version: '2'
services:
    backend:
      build:
        context: ./
        dockerfile: Dockerfile
      ports:
        - 8080:8080
    ouath2server:
      build:
        context: src/main/java/com/bachelor/vju_vm_apla2/Config/Security
        dockerfile: Dockerfile
      ports:
        - 8282:8282