
# compose for the frontend && backend application, if you want complete independce from the frontend, you can comment out line 4 - 8
services:

  frontend:
    image: frontend #note: THIS MUST BE CREATED BY THE FRONTEND FIRST see the dockerfile https://github.com/Bad-chelor-ITPE3200/NAV-IT-SIF-bachelor-frontend/blob/main/Dockerfile
    command: npm start
    ports:
      - "3000:3000"
#    networks:
#      - oauth2server
  backend:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"

    environment:
       FRONTEND.URL: localhost
       FRONTEND.PORT: 3000
       OUATH2.URL: mock-oauth2-server
       OUATH2.PORT: 8282

  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server:2.1.0
    ports:
      - "8282:8282"
    volumes:
      - ./src/main/resources/application.yaml:/app/application.yaml
#      to use the right ouath2server in the frontend:
#    networks:
#      oauth2server:
#        aliases:
#          - ouath2server
    environment:
      LOG_LEVEL: "debug"
      SERVER_PORT: 8282 #todo configure global variable
