version: '3.7'
services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 8080:8080
    links:
      -  mock-oauth2-server
  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server:2.1.0
    ports:
      - 8282:8282
