

http.proxy.parametername: notused

no.nav.security.jwt:
  expirythreshold: 10 #threshold in minutes until token expires
  issuer:
    issuer1:
      discovery-url: ${OUATH2.COMBINED}/default/.well-known/openid-configuration
      accepted_audience: default
    issuer2:
      discovery-url: ${mock-oauth2-server.combined}/default/.well-known/openid-configuration
      accepted_audience: default

logging.level:
  org.springframework: INFO
  no.nav: DEBUG
FRONTEND:
  COMBINED: http://${FRONTEND.URL}:${FRONTEND.PORT}
  URL: localhost
  PORTS: 3000
mock-oauth2-server:
  url: localhost
  port: 8282
  combined: http://${mock-oauth2-server.url}:${mock-oauth2-server.port}
  token-url: ${mock-oauth2-server.combined}/default/token
  clientId: dittClientId
  clientSecret: dinClientSecret

wiremock:
  url: localhost
  port: 8081
  combined: http://${WIREMOCK.url}:${WIREMOCK.port}