

http.proxy.parametername: notused
spring:
  main:
    allow-bean-definition-overriding: true

no.nav.security.jwt:
  expirythreshold: 10 #threshold in minutes until token expires
  issuer:
    issuer1:
      discovery-url: ${mock-oauth2-server.combined}/default/.well-known/openid-configuration
      accepted_audience: default
    issuer2:
      discovery-url: ${mock-oauth2-server.combined}/default/.well-known/openid-configuration
      accepted_audience: default
  client:
    registration:
      demoserver1:
        token-endpoint-url: ${mock-oauth2-server.token-url}
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: scope3, scope4
        authentication:
          client-id: ${mock-oauth2-server.clientId}
          client-secret: ${mock-oauth2-server.clientSecret}
          client-auth-method: client_secret_basic


spring:
  jackson:
    default-property-inclusion: non_null


logging.level:
  org.springframework: INFO
  no.nav: DEBUG
FRONTEND:
  COMBINED: http://${FRONTEND.URL}:${FRONTEND.PORT}
  URL: localhost
  PORTS: 3000
mock-oauth2-server:
  url: mock-oauth2-server
  port: 8282
  combined: http://${mock-oauth2-server.url}:${mock-oauth2-server.port}
  token-url: ${mock-oauth2-server.combined}/default/token
  clientId: dittClientId
  clientSecret: dinClientSecret

db-saf:
  url: localhost
  port: 8081
  combined: http://${db-saf.url}:${db-saf.port}
  Service: ${db-saf.combined}/mock # <- this can be changed to the  right endpoint in the url
  files: .

db-dok:
    url: localhost
    port: 8081
    combined: http://${db-dok.url}:${db-dok.port}
    service: ${db-dok.combined}/mock