

http.proxy.parametername: notused

no.nav.security.jwt:
  expirythreshold: 10 #threshold in minutes until token expires
  issuer:
    issuer1:
      discovery-url: ${OUATH2.COMBINED}/default/.well-known/openid-configuration
      accepted_audience: default
    issuer2:
      discovery-url: ${OUATH2.COMBINED}/default/.well-known/openid-configuration
      accepted_audience: default
logging.level:
  org.springframework: INFO
  no.nav: DEBUG
FRONTEND:
  COMBINED: http://${FRONTEND.URL}:${FRONTEND.PORT}
  URL: localhost
  PORTS: 3000
OUATH2:
  COMBINED: http://${OUATH2.URL}:${OUATH2.PORT}  #todo: figure out what this should be changed to -> to a dockerrized ouath2server?
  URL: mock-oauth2-server #what are the docker ip adress->does this work???
  PORT: 8282
  VERSION: 2.1.0
WIREMOCK:
  url: localhost
  port: 8081
  combined: http://${WIREMOCK.url}:${WIREMOCK.port}