

http.proxy.parametername: notused

no.nav.security.jwt:
  expirythreshold: 10 #threshold in minutes until token expires
  issuer:
    issuer1:
      discovery-url: http://${mock-oauth2-server.url}:${mock-oauth2-server.port}/default/.well-known/openid-configuration
      accepted_audience: default
    issuer2:
      discovery-url: http://${mock-oauth2-server.url}:${mock-oauth2-server.port}/default/.well-known/openid-configuration
      accepted_audience: default
logging.level:
  org.springframework: INFO
  no.nav: DEBUG
FRONTEND:
  COMBINED: http://${FRONTEND.URL}:${FRONTEND.PORT}
  URL: localhost
  PORT: 3000
OUATH2:
  COMBINED: http://${OUATH2.URL}:${OUATH2.PORT}
  URL: localhost
  PORT: 8282