

http.proxy.parametername: notused
spring:
  main:
    allow-bean-definition-overriding: true

no.nav.security.jwt:
  expirythreshold: 10 #threshold in minutes until token expires
  issuer:
    issuer1:
      discovery-url: https://bachelor.kinde.com/.well-known/openid-configuration
      accepted_audience: https://bachelor.kinde.com/api
    issuer2:
      discovery-url: https://bachelor.kinde.com/.well-known/openid-configuration
      accepted_audience: https://bachelor.kinde.com/api
  client:
    registration:
      demoserver1:
        token-endpoint-url: ${mock-oauth2-server.token-url}
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: scope3, scope4
        authentication:
          client-id: ${mock-oauth2-server.clientId}
          client-secret: ${mock-oauth2-server.clientSecret}
          client-auth-method: client_secret_basic

logging.level:
  org.springframework: INFO
  no.nav: DEBUG
FRONTEND:
  COMBINED: http://${FRONTEND.URL}:${FRONTEND.PORT}
  URL: localhost
  PORT: 3000

mock-oauth2-server:
  url: mock-oauth2-server
  port: 8282
  combined: https://bachelor.kinde.com
  token-url: ${mock-oauth2-server.combined}/default/token


wiremock-saf:
  url: localhost
  port: 8081
  combined: http://${wiremock-saf.url}:${wiremock-saf.port}
  Service: ${wiremock-saf.combined} # <- this can be changed to the  right endpoint in the url
  files: .

wiremock-dok:
    url: localhost
    port: 8081
    combined: http://${wiremock-dok.url}:${wiremock-dok.port}
    service: ${wiremock-dok.combined}
